name: streaming_marketing
version: "1.0.0"
profile: streaming_marketing
model-paths: ["models"]
models:
  streaming_marketing:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
